[versions]
agp = "9.0.1"
coreKtx = "1.17.0"
appcompat = "1.7.1"
material = "1.13.0"
uiText = "1.10.3"
runtimeSaveable = "1.10.3"
uiTest = "1.10.3"
documentfile = "1.1.0"
codeview = "1.3.9"
chaquopy = "17.0.0"
animationCore = "1.10.3"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }
androidx-runtime-saveable = { group = "androidx.compose.runtime", name = "runtime-saveable", version.ref = "runtimeSaveable" }
androidx-ui-test = { group = "androidx.compose.ui", name = "ui-test", version.ref = "uiTest" }
androidx-documentfile = { group = "androidx.documentfile", name = "documentfile", version.ref = "documentfile" }
codeview = { module = "io.github.amrdeveloper:codeview", version.ref = "codeview" }
androidx-animation-core = { group = "androidx.compose.animation", name = "animation-core", version.ref = "animationCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
chaquopy = { id = "com.chaquo.python", version.ref = "chaquopy" }
